### ISSUE TITLE
MyAQL启动失败

### ISSUE THREAD

**Issue by musicbugcuhk** [coze-dev/coze-studio#95]
<img width="602" height="513" alt="Image" src="https://github.com/user-attachments/assets/a3bf7883-7aec-4d01-b19e-800d83134b3c" />

**Comment by musicbugcuhk** [comment]
运行数据库时提示：
错误："Workflow execution failure: execute SQL failed: failed to execute SQL: Error 1406 (22001): Data too long for column 'f_3' at row 1"

**Comment by junwen-lee** [comment]
@musicbugcuhk Thank you for your feedback,this issue has been fixed in: #129

**Comment by musicbugcuhk** [comment]
thank u! after I rewrite the files according to ur feedback and restart it, I find it still doesn't work.

**Comment by liuyunchao-1998** [comment]
@musicbugcuhk 重新创建一个数据库再导入数据试试，因为原有的数据库已经创建完毕，f_3列的类型已经被设置为varchar(255)

**Comment by musicbugcuhk** [comment]
I created a new DB, but it still doesn't work. 错误："Workflow execution failure: execute SQL failed: failed to execute SQL: Error 1406 (22001): Data too long for column 'f_2' at row 1"

**Comment by liuyunchao-1998** [comment]
@musicbugcuhk 要写入的数据是什么样的呢，会超过65535字节吗，因为我们string列底层用的是TEXT，最大65535字节

**Comment by musicbugcuhk** [comment]
写入的数据是1000个中文字符，coze在线的工作流中的数据库存储是正常的。

**Comment by hi-pender** [comment]
> I created a new DB, but it still doesn't work. 错误："Workflow execution failure: execute SQL failed: failed to execute SQL: Error 1406 (22001): Data too long for column 'f_2' at row 1"

修改代码后，需要重新构建镜像运行。 确定下运行的软件版本是否更新哈

**Comment by liuyunchao-1998** [comment]
@musicbugcuhk 目前还有问题不
